require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NewsPostsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # NewsPost. As you add validations to NewsPost, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewsPostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all news_posts as @news_posts" do
      news_post = NewsPost.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:news_posts)).to eq([news_post])
    end
  end

  describe "GET #show" do
    it "assigns the requested news_post as @news_post" do
      news_post = NewsPost.create! valid_attributes
      get :show, params: {id: news_post.to_param}, session: valid_session
      expect(assigns(:news_post)).to eq(news_post)
    end
  end

  describe "GET #new" do
    it "assigns a new news_post as @news_post" do
      get :new, params: {}, session: valid_session
      expect(assigns(:news_post)).to be_a_new(NewsPost)
    end
  end

  describe "GET #edit" do
    it "assigns the requested news_post as @news_post" do
      news_post = NewsPost.create! valid_attributes
      get :edit, params: {id: news_post.to_param}, session: valid_session
      expect(assigns(:news_post)).to eq(news_post)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new NewsPost" do
        expect {
          post :create, params: {news_post: valid_attributes}, session: valid_session
        }.to change(NewsPost, :count).by(1)
      end

      it "assigns a newly created news_post as @news_post" do
        post :create, params: {news_post: valid_attributes}, session: valid_session
        expect(assigns(:news_post)).to be_a(NewsPost)
        expect(assigns(:news_post)).to be_persisted
      end

      it "redirects to the created news_post" do
        post :create, params: {news_post: valid_attributes}, session: valid_session
        expect(response).to redirect_to(NewsPost.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved news_post as @news_post" do
        post :create, params: {news_post: invalid_attributes}, session: valid_session
        expect(assigns(:news_post)).to be_a_new(NewsPost)
      end

      it "re-renders the 'new' template" do
        post :create, params: {news_post: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested news_post" do
        news_post = NewsPost.create! valid_attributes
        put :update, params: {id: news_post.to_param, news_post: new_attributes}, session: valid_session
        news_post.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested news_post as @news_post" do
        news_post = NewsPost.create! valid_attributes
        put :update, params: {id: news_post.to_param, news_post: valid_attributes}, session: valid_session
        expect(assigns(:news_post)).to eq(news_post)
      end

      it "redirects to the news_post" do
        news_post = NewsPost.create! valid_attributes
        put :update, params: {id: news_post.to_param, news_post: valid_attributes}, session: valid_session
        expect(response).to redirect_to(news_post)
      end
    end

    context "with invalid params" do
      it "assigns the news_post as @news_post" do
        news_post = NewsPost.create! valid_attributes
        put :update, params: {id: news_post.to_param, news_post: invalid_attributes}, session: valid_session
        expect(assigns(:news_post)).to eq(news_post)
      end

      it "re-renders the 'edit' template" do
        news_post = NewsPost.create! valid_attributes
        put :update, params: {id: news_post.to_param, news_post: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested news_post" do
      news_post = NewsPost.create! valid_attributes
      expect {
        delete :destroy, params: {id: news_post.to_param}, session: valid_session
      }.to change(NewsPost, :count).by(-1)
    end

    it "redirects to the news_posts list" do
      news_post = NewsPost.create! valid_attributes
      delete :destroy, params: {id: news_post.to_param}, session: valid_session
      expect(response).to redirect_to(news_posts_url)
    end
  end

end
